version: "3.3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - network
    volumes:
      - data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}
    networks:
      - network
    volumes:
      - .:/app

volumes:
  data: {}

networks:
  network: